version: "3.9"

services:
  synapse:
    image: matrixdotorg/synapse:latest
    ports: ["8008:8008"]
    restart: unless-stopped
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      MAS_SHARED_SECRET: ${MAS_SHARED_SECRET}
      MACAROON_KEY: ${MACAROON_KEY}
      SERVER_NAME: ${SERVER_NAME}
    volumes:
      - synapse-data:/data
      - ./homeserver.yaml:/data/homeserver.yaml:ro

volumes:
  synapse-data:
