http:
  public_base: "https://mas-production-9d06.up.railway.app/"
  listeners:
    - name: web
      resources:
        - name: discovery
        - name: human
        - name: oauth
        - name: compat
        - name: graphql
        - name: assets
      binds:
        - address: "[::]:8008"

database:
  uri: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"

secrets:
  encryption: "${MAS_ENCRYPTION_SECRET}"
  keys:
    - kid: "primary"
      key: "${MAS_SIGNING_KEY}"

matrix:
  homeserver: "https://synapse-production-e1f9.up.railway.app"
  secret: "${MAS_SHARED_SECRET}"
  endpoint: "https://synapse-production-e1f9.up.railway.app"

clients:
  - client_id: "synapse"
    client_auth_method: "client_secret_basic"
    client_secret: "${MAS_SHARED_SECRET}"

templates:
  path: /usr/local/share/mas-cli/templates
  assets_manifest: /usr/local/share/mas-cli/manifest.json

branding:
  service_name: "My Matrix Server"
