http:
  public_base: "https://mas-production-9d06.up.railway.app/"
  listeners:
    - name: web
      resources:
        - name: discovery
        - name: human
        - name: oauth
        - name: compat
        - name: graphql
        - name: assets
      binds:
        - address: "[::]:8008"

database:
  uri: "postgresql://postgres:BjUtajUuXkRKPnugsQzZULGUxdijseLX@postgres.railway.internal:5432/railway"

secrets:
  encryption: "8f7e6d5c4b3a29180f7e6d5c4b3a29180f7e6d5c4b3a29180f7e6d5c4b3a2918"
  keys:
    - kid: "primary"
      key: "i3+dscLzIOzXiLlrqoENwWkEs6oAdCDuAPgIze9/UBM="

matrix:
  homeserver: "https://synapse-production-e1f9.up.railway.app"
  secret: "JkD92LsKp0Q7A3xM"
  endpoint: "https://synapse-production-e1f9.up.railway.app"

clients:
  - client_id: "01JKMN2QRSTUVWXYZ012345678"
    client_auth_method: "client_secret_basic"
    client_secret: "JkD92LsKp0Q7A3xM"

templates:
  path: /usr/local/share/mas-cli/templates
  assets_manifest: /usr/local/share/mas-cli/manifest.json

branding:
  service_name: "My Matrix Server"
