version: "3.9"

services:
  mas:
    image: ghcr.io/element-hq/matrix-authentication-service:latest
    ports: ["8008:8008"]
    restart: unless-stopped
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      MAS_SERVER_NAME: ${SERVER_NAME}
      MAS_SHARED_SECRET: ${MAS_SHARED_SECRET}
      MAS_LOG_LEVEL: info
